import 'package:youtube/model/post.dart';

final List<Post> posts = [
  Post(
    id: 1,
    profile: "assets/images/menu1.jpg",
    thumbnail: "assets/images/thumbnail1.jpg",
    username: "Lionsgate Movies",
    title: "About My Father (2023) Official Trailer",
    date: "5 days ago",
    likeCount: "50K",
    subscriberCount: "1.93M",
    videoDuration: "2:47",
    videoUrl: "assets/videos/video1.mp4",
    view: "7.3M",
  ),
  Post(
    id: 2,
    profile: "assets/images/menu2.jpg",
    thumbnail: "assets/images/thumbnail2.jpg",
    username: "ONE Media",
    title: "AIR Trailer (2023) Ben Affleck, Matt Damon",
    date: "2 weeks ago",
    likeCount: "13K",
    subscriberCount: "4.39M",
    videoDuration: "2:28",
    videoUrl: "assets/videos/video2.mp4",
    view: "1.2M",
  ),
  Post(
    id: 3,
    profile: "assets/images/menu3.jpg",
    thumbnail: "assets/images/thumbnail3.jpg",
    username: "Teaser PRO",
    title: "SPIDER-MAN: NEW HOME (2024) - FIRST TRAILER",
    date: "2 weeks ago",
    likeCount: "8.3K",
    subscriberCount: "1.05M",
    videoDuration: "2:50",
    videoUrl: "assets/videos/video3.mp4",
    view: "1.2M",
  ),
  Post(
    id: 4,
    profile: "assets/images/menu4.jpg",
    thumbnail: "assets/images/thumbnail4.jpg",
    username: "Movie Coverage",
    title: "RARE OBJECTS Trailer (2023) Katie Holmes, Alan Cumming",
    date: "5 hours ago",
    likeCount: "252",
    subscriberCount: "3.25M",
    videoDuration: "2:23",
    videoUrl: "assets/videos/video4.mp4",
    view: "6.9K",
  ),
  Post(
    id: 5,
    profile: "assets/images/menu5.jpg",
    thumbnail: "assets/images/thumbnail5.jpg",
    username: "Movie Trailers Source",
    title: "FUBAR Official Teaser Trailer (2023)",
    date: "5 hours ago",
    likeCount: "368",
    subscriberCount: "2.38M",
    videoDuration: "0:41",
    videoUrl: "assets/videos/video5.mp4",
    view: "19K",
  ),
];
